### PR TITLE
Allow to easily customize number of digits for JSON serialization

### PR DESCRIPTION
**Pull request by kirillseva**
by setting `options(httr.digits = desired_number_of_digits)`

### CODE REVIEW

**Comment by kirillseva** [comment]
No idea why travis is failing, trivial change and tests pass locally

**Comment by hadley** [comment]
I think it is a really really really bad idea to use options in this way.

**Comment by kirillseva** [comment]
@hadley What do you think would be a good interface for exposing this flag from jsonlite to httr? I'm willing to make it right, seems like a useful feature to have

**Comment by hadley** [comment]
It doesn't really seem that useful to me.  I'd rather add a new encoding type, say "raw", that let you encode the json yourself so you could do whatever you want with it.

**Pull request closed without merging**
