### PR TITLE
tumblr

### PR DESCRIPTION
**Pull request by isomorphisms**
https://www.tumblr.com/docs/en/api/v2#auth

### CODE REVIEW

**Comment by hadley** [comment]
Could you please match the style of the other entries, and add a bullet point to NEWS?

**Comment by hadley** [comment]
It would also be useful to add a full demo to the demos directory

**Comment by isomorphisms** [comment]
Sure. Should I also change twitter, vimeo, and yahoo to look like google and facebook?

**Comment by hadley** [comment]
Thanks!

**Pull request closed without merging**
